-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS M
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS T
JOIN REST_INFO R
ON T.FOOD_TYPE = R.FOOD_TYPE
WHERE R.FAVORITES = M
ORDER BY FOOD_TYPE DESC;