-- 코드를 입력하세요
SELECT C.APNT_NO, A.PT_NAME, A.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM PATIENT A
JOIN DOCTOR B
JOIN APPOINTMENT C
ON A.PT_NO = C.PT_NO
AND B.DR_ID = C.MDDR_ID
WHERE C.MCDP_CD = 'CS'
AND DATE_FORMAT(C.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
AND C.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC;