-- 코드를 입력하세요
SELECT CAR_TYPE, COUNT(CAR_TYPE) AS CARS
FROM (
    SELECT CAR_TYPE, OPTIONS
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE OPTIONS LIKE "%시트%"
) AS A
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;
